<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TransactionFlow.Worker-079b6f79-5c32-48b7-a123-56e3e0e6f4aa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransactionFlow.Application\TransactionFlow.Application.csproj" />
    <ProjectReference Include="..\TransactionFlow.Contracts\TransactionFlow.Contracts.csproj" />
    <ProjectReference Include="..\TransactionFlow.Domain\TransactionFlow.Domain.csproj" />
    <ProjectReference Include="..\TransactionFlow.Infrastructure\TransactionFlow.Infrastructure.csproj" />
  </ItemGroup>
</Project>
